spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  
    show-sql: true
  
      

  