server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      

  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?createDatabaseIfNotExist=true
    data-username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


