spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming: physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  
    show-sql: true
security:
    oauth2:
        resource:
            token-info-uri: http://localhost:9191/oauth/check_token
        client:
            client-id: mobile
            client-secret: pin 
  
      

  